server.port=${PORT:8080}
spring.data.mongodb.uri=mongodb+srv://polisettiindira0_db_user:Rt8dmyDqOBK4h242@cluster0.jmjeac7.mongodb.net/elevatordb?appName=Cluster0
spring.data.mongodb.database=elevatordb